{% set name = "conda-press" %}
{% set version = "0.0.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/regro/conda-press/releases/download/{{ version }}/conda-press-{{ version }}.tar.gz
  sha256: 32aa8eb7553b98c5a8e15a3e8ae6e42d2dd43a2e47c0344cc0c526e68aaa35e8

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"
  skip: true  # [py<35]

requirements:
  host:
    - python
    - pip
  run:
    - python
    - conda
    - requests
    - xonsh
    - lazyasd
    - ruamel.yaml
    - tqdm
    - binutils  # [unix]
    - patchelf  # [linux]
    - dataclasses  # [py < 37]

test:
  imports:
    - conda_press
  commands:
    - conda press --help

about:
  home: https://github.com/regro/conda-press
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: 'Press conda packages into wheels'

extra:
  recipe-maintainers:
    - scopatz
    - marcelotrevisani
