{% set name = "conda-press" %}
{% set version = "0.0.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/regro/conda-press/releases/download/{{ version }}/conda-press-{{ version }}.tar.gz
  sha256: f631715c452ce59379600bb6d4b976371477ba6f42e78c4441ffc20d491e01d6

build:
  number: 3
  script: "{{ PYTHON }} -m pip install . -vv"
  skip: true  # [py<35]

requirements:
  host:
    - python
    - pip
  run:
    - python
    - conda
    - requests
    - xonsh
    - lazyasd
    - ruamel.yaml
    - tqdm
    - binutils  # [unix]
    - patchelf  # [linux]
    - dataclasses  # [py < 37]

test:
  imports:
    - conda_press
  commands:
    - conda press --help

about:
  home: https://github.com/regro/conda-press
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: 'Press conda packages into wheels'

extra:
  recipe-maintainers:
    - mfansler
    - scopatz
    - marcelotrevisani
