travis:
  secure:
    BINSTAR_TOKEN: JXzH76ATNfDc7VASVu51K/s17oEBVz9oXCTiT0z190PBpYSw7osX9kGxXMoPyR+MyvBORQhZILkIjReNLF+mpq9obcXmDViLJe1+6GkZHAjgnHT1iHgn6EfCoqvX3pS0fgq5USFGufcD5TiDVjOnJGADYiaBpsU9A92lZvUsQ7iSyiZkP/6/H+BzGx3772PFLu5xLPIyHuNa+g+xUBK/yDg/WoCZW/+vbJucnsjPjqAU2YggA7utd1Ycv6SdJKrOpiObKwMBJwZxHPNLVlVMMeZtuQ//WJAwHcGREk1qMDDDXWPSa1bUfJSpbhGAatkDyoSrHVjextmzFZWxQw28xMfUztzysoNM56V+Dopr82ksipaSEpYWmUKTaFKQyUg6oFkFZpcsWcc84exvsLV1ZSu+Z4o3CRCPB2mu6YY4J3UTSWBm1YhVpknmGDjfxqwvv4oZK6AIWLU95tEKvkGCYGHoSO5R+QvMs5y+9tuN+0elFpZuPa65eGRMATASSEULLnDrjNjKk/6oGCzxkePSvavZ/OTCG4oB8aDmu/EuXgdNgXVFgoRPE34ivxPvAOZ2coYgkCpbvV1Qii5wU3NFxLq+VbHSZjI9fOvVmoc9khxJXYS7Plti+eSNwBShizxjybzEkFXZXshDzF8Bb10VyUEIGGgkuoYVMuFy+Ux9KRc=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
